// utils/rbxmxToLua.js
const fs = require('fs');
const xml2js = require('xml2js');

/**
 * Converts a .rbxmx file to Roblox Lua code
 * @param {string} filePath - Path to the .rbxmx file
 * @returns {Promise<string>} Generated Lua code
 */
async function parseRbxmxToLua(filePath) {
  const xml = fs.readFileSync(filePath, 'utf8');
  const parser = new xml2js.Parser({
    explicitArray: false,
    ignoreAttrs: false,
    attrkey: 'attrs',
    charkey: 'value',
    trim: true,
  });

  const result = await parser.parseStringPromise(xml);
  const items = Array.isArray(result.roblox.Item) ? result.roblox.Item : [result.roblox.Item];

  let luaCode = '-- Generated by rbxmx-to-lua converter\n\n';
  let instanceCounter = 0;
  const instanceMap = new Map(); // referent → variable name

  function getVariableName(className, referent) {
    if (referent && instanceMap.has(referent)) {
      return instanceMap.get(referent);
    }
    const name = className + (++instanceCounter);
    if (referent) instanceMap.set(referent, name);
    return name;
  }

  function convertValue(propName, value, propType) {
    if (!value && value !== 0) return 'nil';

    switch (propType) {
      case 'string':
        return `"${value.replace(/"/g, '\\"')}"`;

      case 'number':
      case 'bool':
        return value.toString();

      case 'UDim2':
        const [scaleX, offsetX, scaleY, offsetY] = value.match(/[-0-9.]+/g);
        return `UDim2.new(\( {scaleX}, \){offsetX}, \( {scaleY}, \){offsetY})`;

      case 'Color3':
        const [r, g, b] = value.match(/[-0-9.]+/g);
        return `Color3.new(\( {r}, \){g}, ${b})`;

      case 'Vector3':
        const [x, y, z] = value.match(/[-0-9.]+/g);
        return `Vector3.new(\( {x}, \){y}, ${z})`;

      case 'Font':
        const face = value.Font?.value || 'SourceSans';
        const weight = value.FontWeight?.value || 400;
        const style = value.FontStyle?.value || 'Normal';
        return `Enum.Font.${face.replace(/ /g, '')}`; // Simplified

      case 'Enum':
        const enumType = propName; // e.g., TextXAlignment
        const enumValue = value.split('.').pop();
        return `Enum.\( {enumType}. \){enumValue}`;

      default:
        if (typeof value === 'string' && value.startsWith('{')) {
          return `"${value}"`; // Token, Content, etc.
        }
        return `"${value}"`;
    }
  }

  function processItem(item, parentVar = null) {
    const className = item.attrs?.class || 'Instance';
    const referent = item.attrs?.referent;
    const varName = getVariableName(className, referent);

    luaCode += `local \( {varName} = Instance.new(" \){className}")\n`;

    // Name property
    if (item.Properties?.Name?.value) {
      luaCode += `\( {varName}.Name = " \){item.Properties.Name.value}"\n`;
    }

    // Other properties
    if (item.Properties) {
      for (const [propName, propData] of Object.entries(item.Properties)) {
        if (propName === 'Name') continue;

        const propValue = propData.value ?? propData;
        const propType = propData.attrs?.type || (typeof propValue);

        if (propValue !== undefined && propValue !== null) {
          const luaValue = convertValue(propName, propValue.toString(), propType);
          luaCode += `\( {varName}. \){propName} = ${luaValue}\n`;
        }
      }
    }

    // Parent (will set later to avoid order issues)
    if (parentVar) {
      luaCode += `\( {varName}.Parent = \){parentVar}\n`;
    }

    // Children
    if (item.Item) {
      const children = Array.isArray(item.Item) ? item.Item : [item.Item];
      children.forEach(child => processItem(child, varName));
    }

    luaCode += '\n';
  }

  // Process all top-level items
  items.forEach(item => processItem(item));

  // Final parenting for top-level (usually to PlayerGui)
  const topLevelVars = [...instanceMap.values()].slice(0, items.length);
  if (topLevelVars.length === 1) {
    luaCode += `${topLevelVars[0]}.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")\n`;
  } else if (topLevelVars.length > 1) {
    luaCode += `-- Multiple top-level objects detected. Parent manually:\n`;
    topLevelVars.forEach(v => luaCode += `-- ${v}.Parent = game.Players.LocalPlayer.PlayerGui\n`);
  }

  return luaCode;
}

module.exports = { parseRbxmxToLua };
